using Microsoft.AspNetCore.Mvc;
using Microsoft.IdentityModel.Tokens;
using System.IdentityModel.Tokens.Jwt;
using System.Security.Cryptography;
using System.Text;
using API.Data;
using API.Models;
using API.Models.DTOs;
using API.Services;
using Microsoft.EntityFrameworkCore;

namespace API.Controllers
{
    [ApiController]
    [Route("api/[controller]")]
    public class AuthController : ControllerBase
    {
        private readonly ApplicationDbContext _context;
        private readonly IConfiguration _configuration;
        private readonly IEmailService _emailService;
        private readonly IPasswordGenerationService _passwordGenerationService;

        public AuthController(ApplicationDbContext context, IConfiguration configuration, IEmailService emailService, IPasswordGenerationService passwordGenerationService)
        {
            _context = context;
            _configuration = configuration;
            _emailService = emailService;
            _passwordGenerationService = passwordGenerationService;
        }

        [HttpPost("register")]
        public async Task<ActionResult<AuthResponse>> Register(RegisterRequest request)
        {
            try
            {
                // Validate required fields
                if (string.IsNullOrWhiteSpace(request.Name) || 
                    string.IsNullOrWhiteSpace(request.Email) || 
                    string.IsNullOrWhiteSpace(request.Password) ||
                    string.IsNullOrWhiteSpace(request.ProfileImage))
                {
                    return BadRequest(new AuthResponse
                    {
                        Success = false,
                        Message = "Name, email, password, and profile image are required"
                    });
                }

                // Check if user already exists
                if (_context.Users.Any(u => u.Email == request.Email && u.UniversityId==request.UniversityId))
                {
                    return BadRequest(new AuthResponse
                    {
                        Success = false,
                        Message = "User already exists"
                    });
                }

                // Generate auto-generated password using the service
                var autoGeneratedPassword = _passwordGenerationService.GeneratePassword();

                // Create new user
                var user = new User
                {
                    Name = request.Name,
                    Email = request.Email,
                    PasswordHash = HashPassword(request.Password),
                    AutoGeneratedPassword = autoGeneratedPassword,
                    UserType = request.UserType,
                    UniversityId = request.UniversityId,
                    Phone = request.Phone,
                    Address = request.Address,
                    ProfileImage = request.ProfileImage,
                    IsActive = false
                };

                _context.Users.Add(user);
                await _context.SaveChangesAsync();

                // Send auto-generated password email
                try
                {
                    await _emailService.SendAutoGeneratedPasswordAsync(user.Email, user.Name, autoGeneratedPassword);
                }
                catch (Exception ex)
                {
                    // Log the error but don't fail the registration
                    Console.WriteLine($"Failed to send email: {ex.Message}");
                }

                var token = GenerateJwtToken(user);

                return Ok(new AuthResponse
                {
                    Success = true,
                    Message = user.IsActive 
                        ? "User registered successfully" 
                        : "Registration successful! Your account is pending approval by the coordinator.",
                    Token = token,
                    User = new UserDto
                    {
                        Id = user.Id,
                        Name = user.Name,
                        Email = user.Email,
                        UserType = user.UserType,
                        UniversityId = user.UniversityId,
                        DepartmentId = user.DepartmentId,
                        Phone = user.Phone,
                        Address = user.Address,
                        ProfileImage = user.ProfileImage,
                        IsActive = user.IsActive,
                        IsApproved = user.IsApproved,
                    }
                });
            }
            catch (Exception ex)
            {
                return StatusCode(500, new AuthResponse
                {
                    Success = false,
                    Message = ex.Message
                });
            }
        }

        [HttpPost("login")]
        public async Task<ActionResult<AuthResponse>> Login(LoginRequest request)
        {
            try
            {
                var user = _context.Users.FirstOrDefault(u => u.Email == request.Email);

                if (user == null || !VerifyPassword(request.Password, user.PasswordHash))
                {
                    return Unauthorized(new AuthResponse
                    {
                        Success = false,
                        Message = "Invalid credentials"
                    });
                }

                if (!user.IsActive)
                {
                    return BadRequest(new AuthResponse
                    {
                        Success = false,
                        Message = "Your account is pending approval by the coordinator or has been deactivated."
                    });
                }

                var token = GenerateJwtToken(user);

                return Ok(new AuthResponse
                {
                    Success = true,
                    Message = "Login successful",
                    Token = token,
                    User = new UserDto
                    {
                        Id = user.Id,
                        Name = user.Name,
                        Email = user.Email,
                        UserType = user.UserType,
                        UniversityId = user.UniversityId,
                        DepartmentId = user.DepartmentId,
                        Phone = user.Phone,
                        Address = user.Address,
                        ProfileImage = user.ProfileImage,
                        IsActive = user.IsActive
                    }
                });
            }
            catch (Exception ex)
            {
                return StatusCode(500, new AuthResponse
                {
                    Success = false,
                    Message = ex.Message
                });
            }
        }

        [HttpGet("invitation-details")]
        public async Task<ActionResult<InvitationDetailsDto>> GetInvitationDetails([FromQuery] string token)
        {
            try
            {
                if (string.IsNullOrWhiteSpace(token))
                {
                    return BadRequest(new { success = false, message = "Token is required" });
                }

                var invitation = _context.Invitations
                    .Include(i => i.University)
                    .Include(i => i.Department)
                    .FirstOrDefault(i => i.Token == token);

                if (invitation == null)
                {
                    return NotFound(new { success = false, message = "Invitation not found" });
                }

                if (invitation.IsUsed)
                {
                    return BadRequest(new { success = false, message = "Invitation has already been used" });
                }

                if (invitation.ExpiresAt < DateTime.UtcNow)
                {
                    return BadRequest(new { success = false, message = "Invitation has expired" });
                }

                return Ok(new InvitationDetailsDto
                {
                    Email = invitation.Email,
                    UniversityId = invitation.UniversityId,
                    UniversityName = invitation.University?.UniversityName ?? "Unknown University",
                    DepartmentId = invitation.DepartmentId,
                    DepartmentName = invitation.Department?.Name ?? "General"
                });
            }
            catch (Exception ex)
            {
                return StatusCode(500, new { success = false, message = ex.Message });
            }
        }

        [HttpPost("accept-invitation")]
        public async Task<ActionResult<AuthResponse>> AcceptInvitation(AcceptInvitationRequest request)
        {
            try
            {
                if (string.IsNullOrWhiteSpace(request.Token) || 
                    string.IsNullOrWhiteSpace(request.Name) || 
                    string.IsNullOrWhiteSpace(request.Password))
                {
                    return BadRequest(new AuthResponse
                    {
                        Success = false,
                        Message = "Token, Name, and Password are required"
                    });
                }

                var invitation = _context.Invitations.FirstOrDefault(i => i.Token == request.Token);
                if (invitation == null)
                {
                    return BadRequest(new AuthResponse { Success = false, Message = "Invalid invitation token" });
                }

                if (invitation.IsUsed)
                {
                    return BadRequest(new AuthResponse { Success = false, Message = "This invitation has already been used" });
                }

                if (invitation.ExpiresAt < DateTime.UtcNow)
                {
                    return BadRequest(new AuthResponse { Success = false, Message = "This invitation has expired" });
                }

                // Check if user already exists
                if (_context.Users.Any(u => u.Email == invitation.Email))
                {
                    return BadRequest(new AuthResponse
                    {
                        Success = false,
                        Message = "A user with this email address is already registered"
                    });
                }

                // Create new active examiner user
                var user = new User
                {
                    Name = request.Name,
                    Email = invitation.Email,
                    PasswordHash = HashPassword(request.Password),
                    UserType = "examiner",
                    UniversityId = invitation.UniversityId,
                    DepartmentId = invitation.DepartmentId,
                    Phone = request.Phone,
                    Address = request.Address,
                    ProfileImage = request.ProfileImage,
                    IsActive = true // Accounts created via invitation are active immediately
                };

                _context.Users.Add(user);
                invitation.IsUsed = true;
                
                await _context.SaveChangesAsync();

                var token = GenerateJwtToken(user);

                return Ok(new AuthResponse
                {
                    Success = true,
                    Message = "Invitation accepted and account activated successfully",
                    Token = token,
                    User = new UserDto
                    {
                        Id = user.Id,
                        Name = user.Name,
                        Email = user.Email,
                        UserType = user.UserType,
                        UniversityId = user.UniversityId,
                        DepartmentId = user.DepartmentId,
                        Phone = user.Phone,
                        Address = user.Address,
                        ProfileImage = user.ProfileImage,
                        IsActive = user.IsActive
                    }
                });
            }
            catch (Exception ex)
            {
                return StatusCode(500, new AuthResponse
                {
                    Success = false,
                    Message = ex.Message
                });
            }
        }

        private string GenerateJwtToken(User user)
        {
            var securityKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(_configuration["Jwt:Key"]));
            var credentials = new SigningCredentials(securityKey, SecurityAlgorithms.HmacSha256);

            var claims = new[]
            {
                new System.Security.Claims.Claim("id", user.Id.ToString()),
                new System.Security.Claims.Claim("email", user.Email),
                new System.Security.Claims.Claim("userType", user.UserType),
                new System.Security.Claims.Claim(System.Security.Claims.ClaimTypes.Role, user.UserType)
            };

            var token = new JwtSecurityToken(
                issuer: _configuration["Jwt:Issuer"],
                audience: _configuration["Jwt:Audience"],
                claims: claims,
                expires: DateTime.UtcNow.AddMinutes(int.Parse(_configuration["Jwt:ExpirationMinutes"])),
                signingCredentials: credentials
            );

            return new JwtSecurityTokenHandler().WriteToken(token);
        }

        private string HashPassword(string password)
        {
            using (var sha256 = SHA256.Create())
            {
                var hashedBytes = sha256.ComputeHash(Encoding.UTF8.GetBytes(password));
                return Convert.ToBase64String(hashedBytes);
            }
        }

        private bool VerifyPassword(string password, string hash)
        {
            var hashOfInput = HashPassword(password);
            return hashOfInput == hash;
        }
    }
}
