using Microsoft.AspNetCore.Mvc;
using Microsoft.IdentityModel.Tokens;
using System.IdentityModel.Tokens.Jwt;
using System.Security.Cryptography;
using System.Text;
using API.Data;
using API.Models;
using API.Models.DTOs;
using API.Services;

namespace API.Controllers
{
    [ApiController]
    [Route("api/[controller]")]
    public class AuthController : ControllerBase
    {
        private readonly ApplicationDbContext _context;
        private readonly IConfiguration _configuration;
        private readonly IEmailService _emailService;
        private readonly IPasswordGenerationService _passwordGenerationService;

        public AuthController(ApplicationDbContext context, IConfiguration configuration, IEmailService emailService, IPasswordGenerationService passwordGenerationService)
        {
            _context = context;
            _configuration = configuration;
            _emailService = emailService;
            _passwordGenerationService = passwordGenerationService;
        }

        [HttpPost("register")]
        public async Task<ActionResult<AuthResponse>> Register(RegisterRequest request)
        {
            try
            {
                // Validate required fields
                if (string.IsNullOrWhiteSpace(request.Name) || 
                    string.IsNullOrWhiteSpace(request.Email) || 
                    string.IsNullOrWhiteSpace(request.Password) ||
                    string.IsNullOrWhiteSpace(request.ProfileImage))
                {
                    return BadRequest(new AuthResponse
                    {
                        Success = false,
                        Message = "Name, email, password, and profile image are required"
                    });
                }

                // Check if user already exists
                if (_context.Users.Any(u => u.Email == request.Email))
                {
                    return BadRequest(new AuthResponse
                    {
                        Success = false,
                        Message = "User already exists"
                    });
                }

                // Generate auto-generated password using the service
                var autoGeneratedPassword = _passwordGenerationService.GeneratePassword();

                // Create new user
                var user = new User
                {
                    Name = request.Name,
                    Email = request.Email,
                    PasswordHash = HashPassword(request.Password),
                    AutoGeneratedPassword = autoGeneratedPassword,
                    UserType = request.UserType,
                    UniversityId = request.UniversityId,
                    Phone = request.Phone,
                    Address = request.Address,
                    ProfileImage = request.ProfileImage,
                    IsActive = true
                };

                _context.Users.Add(user);
                await _context.SaveChangesAsync();

                // Send auto-generated password email
                try
                {
                    await _emailService.SendAutoGeneratedPasswordAsync(user.Email, user.Name, autoGeneratedPassword);
                }
                catch (Exception ex)
                {
                    // Log the error but don't fail the registration
                    Console.WriteLine($"Failed to send email: {ex.Message}");
                }

                var token = GenerateJwtToken(user);

                return Ok(new AuthResponse
                {
                    Success = true,
                    Message = "User registered successfully",
                    Token = token,
                    User = new UserDto
                    {
                        Id = user.Id,
                        Name = user.Name,
                        Email = user.Email,
                        UserType = user.UserType,
                        UniversityId = user.UniversityId,
                        DepartmentId = user.DepartmentId,
                        Phone = user.Phone,
                        Address = user.Address,
                        ProfileImage = user.ProfileImage
                    }
                });
            }
            catch (Exception ex)
            {
                return StatusCode(500, new AuthResponse
                {
                    Success = false,
                    Message = ex.Message
                });
            }
        }

        [HttpPost("login")]
        public async Task<ActionResult<AuthResponse>> Login(LoginRequest request)
        {
            try
            {
                var user = _context.Users.FirstOrDefault(u => u.Email == request.Email);

                if (user == null || !VerifyPassword(request.Password, user.PasswordHash))
                {
                    return Unauthorized(new AuthResponse
                    {
                        Success = false,
                        Message = "Invalid credentials"
                    });
                }

                var token = GenerateJwtToken(user);

                return Ok(new AuthResponse
                {
                    Success = true,
                    Message = "Login successful",
                    Token = token,
                    User = new UserDto
                    {
                        Id = user.Id,
                        Name = user.Name,
                        Email = user.Email,
                        UserType = user.UserType,
                        UniversityId = user.UniversityId,
                        DepartmentId = user.DepartmentId,
                        Phone = user.Phone,
                        Address = user.Address,
                        ProfileImage = user.ProfileImage
                    }
                });
            }
            catch (Exception ex)
            {
                return StatusCode(500, new AuthResponse
                {
                    Success = false,
                    Message = ex.Message
                });
            }
        }

        private string GenerateJwtToken(User user)
        {
            var securityKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(_configuration["Jwt:Key"]));
            var credentials = new SigningCredentials(securityKey, SecurityAlgorithms.HmacSha256);

            var claims = new[]
            {
                new System.Security.Claims.Claim("id", user.Id.ToString()),
                new System.Security.Claims.Claim("email", user.Email),
                new System.Security.Claims.Claim("userType", user.UserType),
                new System.Security.Claims.Claim(System.Security.Claims.ClaimTypes.Role, user.UserType)
            };

            var token = new JwtSecurityToken(
                issuer: _configuration["Jwt:Issuer"],
                audience: _configuration["Jwt:Audience"],
                claims: claims,
                expires: DateTime.UtcNow.AddMinutes(int.Parse(_configuration["Jwt:ExpirationMinutes"])),
                signingCredentials: credentials
            );

            return new JwtSecurityTokenHandler().WriteToken(token);
        }

        private string HashPassword(string password)
        {
            using (var sha256 = SHA256.Create())
            {
                var hashedBytes = sha256.ComputeHash(Encoding.UTF8.GetBytes(password));
                return Convert.ToBase64String(hashedBytes);
            }
        }

        private bool VerifyPassword(string password, string hash)
        {
            var hashOfInput = HashPassword(password);
            return hashOfInput == hash;
        }
    }
}
