using System.Net;
using System.Net.Mail;

namespace API.Services
{
    public interface IEmailService
    {
        Task SendEmailAsync(string toEmail, string subject, string body);
        Task SendAutoGeneratedPasswordAsync(string toEmail, string userName, string autoGeneratedPassword);
        Task SendAutoGeneratedPasswordWithServiceAsync(string toEmail, string userName);
        Task SendInvitationEmailAsync(string toEmail, string invitationLink);
    }

    public class EmailService : IEmailService
    {
        private readonly IConfiguration _configuration;
        private readonly ILogger<EmailService> _logger;
        private readonly IPasswordGenerationService _passwordGenerationService;

        public EmailService(IConfiguration configuration, ILogger<EmailService> logger, IPasswordGenerationService passwordGenerationService)
        {
            _configuration = configuration;
            _logger = logger;
            _passwordGenerationService = passwordGenerationService;
        }

        public async Task SendEmailAsync(string toEmail, string subject, string body)
        {
            try
            {
                var smtpServer = _configuration["EmailSettings:Host"] ?? _configuration["Email:SmtpServer"];
                var smtpPort = int.Parse(_configuration["EmailSettings:Port"] ?? _configuration["Email:SmtpPort"] ?? "587");
                var senderEmail = _configuration["EmailSettings:Email"] ?? _configuration["Email:SenderEmail"];
                var senderPassword = _configuration["EmailSettings:Password"] ?? _configuration["Email:SenderPassword"];
                var senderName = _configuration["EmailSettings:Displayname"] ?? _configuration["Email:SenderName"] ?? "On-Screen Marking";

                if (string.IsNullOrEmpty(smtpServer))
                {
                    _logger.LogWarning("SMTP Server is not configured. Email was not sent.");
                    return;
                }

                using (var client = new SmtpClient(smtpServer, smtpPort))
                {
                    client.EnableSsl = true;
                    client.Credentials = new NetworkCredential(senderEmail, senderPassword);

                    var mailMessage = new MailMessage
                    {
                        From = new MailAddress(senderEmail, senderName),
                        Subject = subject,
                        Body = body,
                        IsBodyHtml = true
                    };

                    mailMessage.To.Add(toEmail);

                    await client.SendMailAsync(mailMessage);
                    _logger.LogInformation($"Email sent successfully to {toEmail}");
                }
            }
            catch (Exception ex)
            {
                _logger.LogError($"Error sending email to {toEmail}: {ex.Message}");
                throw;
            }
        }

        public async Task SendAutoGeneratedPasswordAsync(string toEmail, string userName, string autoGeneratedPassword)
        {
            var subject = "Your On-Screen Marking Account - Auto-Generated Password";
            var body = $@"
                <html>
                    <body style='font-family: Arial, sans-serif;'>
                        <h2>Welcome to On-Screen Marking Portal</h2>
                        <p>Dear {userName},</p>
                        <p>Your account has been created successfully. Please use the following credentials to log in:</p>
                        <table style='border-collapse: collapse; margin: 20px 0;'>
                            <tr>
                                <td style='padding: 10px; border: 1px solid #ddd; font-weight: bold;'>Email:</td>
                                <td style='padding: 10px; border: 1px solid #ddd;'>{toEmail}</td>
                            </tr>
                            <tr>
                                <td style='padding: 10px; border: 1px solid #ddd; font-weight: bold;'>Password:</td>
                                <td style='padding: 10px; border: 1px solid #ddd;'><code>{autoGeneratedPassword}</code></td>
                            </tr>
                        </table>
                        <p><strong>Important:</strong> Please change your password after your first login for security purposes.</p>
                        <p>If you did not request this account, please contact the administrator.</p>
                        <br/>
                        <p>Best regards,<br/>On-Screen Marking Team</p>
                    </body>
                </html>";

            await SendEmailAsync(toEmail, subject, body);
        }

        public async Task SendAutoGeneratedPasswordWithServiceAsync(string toEmail, string userName)
        {
            var autoGeneratedPassword = _passwordGenerationService.GeneratePassword();
            await SendAutoGeneratedPasswordAsync(toEmail, userName, autoGeneratedPassword);
        }

        public async Task SendInvitationEmailAsync(string toEmail, string invitationLink)
        {
            var subject = "Invitation to join On-Screen Marking Portal";
            var body = $@"
                <html>
                    <body style='font-family: Arial, sans-serif;'>
                        <h2>Welcome to On-Screen Marking Portal</h2>
                        <p>Dear Examiner,</p>
                        <p>You have been invited to join the On-Screen Marking Portal as an examiner.</p>
                        <p>Please click the button below to accept your invitation and complete your registration:</p>
                        <p style='margin: 20px 0;'>
                            <a href='{invitationLink}' style='background-color: #2563eb; color: white; padding: 12px 24px; text-decoration: none; border-radius: 8px; font-weight: bold; display: inline-block;'>Accept Invitation</a>
                        </p>
                        <p>Or copy and paste this URL into your browser:</p>
                        <p><code>{invitationLink}</code></p>
                        <p><strong>Note:</strong> This invitation link will expire in 7 days.</p>
                        <br/>
                        <p>Best regards,<br/>On-Screen Marking Team</p>
                    </body>
                </html>";

            await SendEmailAsync(toEmail, subject, body);
        }
    }
}
